### ISSUE TITLE
File meta data in JSON

### ISSUE THREAD

**Issue by daphne-eu** [daphne-eu/daphne#210]
In GitLab by @pdamme on Mar 8, 2022, 17:46

DAPHNE stores some essential meta data about a file in a *meta data file* (see `src/runtime/local/io/FileMetaData.h`). Those meta data files have a very simple text-based format. However, its semantics is still somewhat cryptic. It would be great to make it more explicit and user-friendly by using a simple JSON-based format.

For instance, the following current meta data file:
```
2,2,0,si64,f64,foo,bar
```
Could become something like:
```
{
  "numRows": 2,
  "numCols": 2,
  "columns": [
    {"name": "foo", "valueType": "si64"},
    {"name": "bar", "valueType": "f64"}
  ]
}
```

A JSON parser library should soon be added via #141.

**Comment by matejmoravec** [comment]
Hello. I would like to work on this issue. :-)

**Comment by pdamme** [comment]
For clarification: Since `FileMetaData` can represent both matrix and frame meta data (which are slightly different), it's not so trivial how to design the JSON-based format. I propose the following:

**Schema of a meta data JSON file**

The JSON file should always contain the following keys:
- `numRows`: integer
- `numCols`: integer

The JSON file should always contain exactly one of the following keys:
- either: `valueType`: string
  Then, `FileMetaData::schema` has one element, `FileMetaData::labels` is empty, and `FileMetaData::isSingleValueType` is `true`.
- or: `schema`: array of objects (`label`: string, `valueType`: string)
  Then, `FileMetaData::schema` and `FileMetaData::labels` are filled with the provided value types/labels, and `FileMetaData::isSingleValueType` is `false`.

The JSON file may optionally contain the following key:
- `numNonZeros`: integer (default: `-1`)

**Examples**

Matrix meta data:

```json
{
  "numRows": 7,
  "numCols": 5,
  "valueType": "f64",
  "numNonZeros": 29
}
```

Frame meta data:

```json
{
  "numRows": 5,
  "numCols": 3,
  "schema": [
    {"label": "foo", "valueType": "si64"},
    {"label": "bar", "valueType": "f64"},
    {"label": "baz", "valueType": "f32"}
  ]
}
```
