### ISSUE TITLE
[Distributed] - Code Structure for the Distributed Runtime (Object Metadata)

### ISSUE THREAD

**Issue by aristotelis96** [daphne-eu/daphne#367]
This issue serves as a place to discuss suggestions and ideas for the implementation of the distributed runtime.

Topic:
In the current implementation the compiler is responsible for issuing the distributed execution (when data will be transfered, when an operation will be executed etc.). There is a WIP to support distributed pipelines (i.e. pipelines similar to what vectorized execution is using) under branch Distributed-ICCS, see also PR #330. In this implementation the runtime is responsible for providing all the workers with the nessacary inputs of a pipeline and then issuing the execution by providing the corresponding IR code of that pipeline to the workers.

This is issue is created to further discuss the following:

1) Metadata support for distributed objects (matrices).
2) Where the logic (transfer/sending/receiving) of the objects should be placed in the code.

Comments:
1- PR #334 introduces a first implementation regarding object metadata, however this is targeted for CUDA/local devices/execution. We need to either extend this or/and introduce a different metadata field that is utilized specifically by the distributed runtime.

2- PR #330 implements the distributed pipelines. For now it is heavily tied to the gRPC framework. We need to adapt/extend these kernels by removing gRPC code and making them more generic for any future communication framework (e.g. MPI).

**Comment by corepointer** [comment]
In our email discussion, the question of how to place code that would distribute data and if it would make sense to separate into code that holds the information where what is placed from the code that uses this information to place the data where it is needed (I hope that sums up the question correctly @aristotelis96).

This is what I believe is "the Daphne" way: 
1. The Daphne compiler decides if it is appropriate to do distributed computation on some input data+code (going by the characteristics of the data and the availability of distributed ops/kernels)
2.  The Daphne compiler not only fuses the distributed pipeline but also inserts distribution primitives (e.g., a broadcast op)
3. At runtime, this broadcast op is executed on the driver/coordinator before starting the fused distributed pipeline
4. The broadcast kernel would use a generic interface to invoke the transfers (e.g., `` alloc->distribute()``)
5. Behind that `` alloc->distribute() `` can be gRPC or MPI or whatnot. 
6. The distribute kernel would then store the info of distribution with the object (e.g., `` inputMatrix->addObjMetaData(alloc)``)
7. At a later stage in the execution, a collect kernel on the coordinator/driver can use that info that is stored in the object meta data (OMD) to do its job. Note that it is for the compiler to decide when it makes sense to issue that operation. More precisely, it gives us a chance to reason about decisions at compile time (which might be augmented by decisions at run time of course - we don't need to restrict ourselves here imho)

In terms of C++ details, this separates concerns but keeps data where it is needed by using abstract interfaces and letting the classes know how to handle their data also hold their data.

To be able to hold all kinds of allocation descriptors in the OMD, we reduce the functionality of the IAllocationDescriptor to just determining which kind of descriptor that actually is. In a second interface, that is also implemented by a certain type of descriptor, we can get more specific and say IDistributed, IGPU, IFPGA etc to add methods that concern these types of operators (e.g., send/receive, transferTo/transferFrom, ...)

A CUDAAllocationDescriptor would get a context object a data pointer and maybe some device preference (e.g., userConfig object) to move that data to a device. Then that descriptor object would be stored in an OMD together with the range information and finally return the result (e.g., the pointer to device memory) to the calling Daphne kernel. That whole functionality is hidden from the Daphne kernel that just calls ``VT* res = matrix->getValues(cuda_descriptor);``

A Daphne kernel on a worker node that uses a CPU kernel would just issue `` VT* res = matrix->getValues(host_descriptor);`` and not be concerned with all the details behind the scenes. In the example case with the broadcast kernel above, this behind the scenes business has already been taken care of and the data should be in the node's host memory.

But the driver/coordinator is indeed concerned with where the data resides. On the one hand, to issue that collect kernel at some point. On the other hand (and this is a rather esoteric example), one could issue our famous ``print()`` kernel on a matrix object and because we stored that information somewhere in an OMD, we could act upon the situation and transfer the data back automatically (as is done in the CUDA case) to have ``print()`` do its job. But I already mentioned in the email conversation that this on demand transfer is a nice side effect and we can still do explicit transfers when we need them (the compiler must know ;-) )

**Comment by aristotelis96** [comment]
Thank you @corepointer for your vaulable help. Your suggestions and examples really help claryfing things up and provide better understanding on how OMD will work. 

I generally agree with what you described as "the Daphne" way. (1) Sounds very good to me. For now we simply re-use code from the VectorizationPass in order to create pipelines, but I agree that Distributed pipelines should have different criteria. Regarding (2) and (7), as you mentioned this could be implemented in the future. For now primitives are handled by runtime within the DistributedWrapper. 

You can check what I've done so far [here](https://github.com/aristotelis96/daphne/tree/Distributed-IAllocationDescriptorDistributed). A few notes: 

1. I followed your suggestion and implemented `IAllocationDescriptorDistributed` which derives from `IAllocationDescriptor`. 
2. I've implemented the gRPC version `AllocationDescriptorDistributedGRPC` which handles the communication using gRPC.
3. Based on what you presented, broadcast/distribute/compute kernels are generic and communication-framework agnostic. They simply  focus on creating/updating the OMD.
4. After updating the OMD the kernel is invoking transfers using the generic interface `IAllocationDescriptorDistributed` which can be implemented by grpc or mpi, etc.
5. For now transferTo/From methods are not imlpemented. Collect primitive is always used by the distributed wrapper and fetches data back to the coordinator after executing a pipeline, therefore it is not necessary to implement transfers for now. I agree with you that this should not always happen and having kernels act upon the situation and transfer the data back sounds like the best plan. I'll work on that as a next step. 

Hopefully these changes will make integration with MPI easier. Happy to hear your suggestions and ideas! 😃 

PS: For now I've placed `IAllocationDescriptorDistributed/GRPC` at `runtime/distributed/coordinator/kernels` due to the fact that they are DistributedRuntime-related. However they might be better placed under `runtime/local/datastructures` or perhaps `runtime/distributed/coordinator/datastructures/`.

**Comment by aristotelis96** [comment]
After discussing with @corepointer and @pdamme there are a few updates regarding the Distributed runtime implementation:

- Distributed meta data will simply hold information regarding where data resides. 
- `AllocationDescriptors` will only implement `transferTo()` and `transferFrom()` functions rather than high-level distributed-related functions (i.e. Broadcasting).
- These high-level primitives (distribute/broadcast) will be included in specific distributed runtime kernels. These kernels will be responsible for modifying the meta data of an object **and** issuing the communication to the workers. Similar to local runtime kernels, for each primitive we'll use templated functions  with differernt partial specilizations for each distributed backend implementation (e.g. gRPC, MPI, etc.).
