### ISSUE TITLE
Vectorize engine crashes when running multiLogReg.daph

### ISSUE THREAD

**Issue by aristotelis96** [daphne-eu/daphne#375]
Script `scripts/algorithms/multiLogRef.daph` seems to work fine for the local runtime. However, when using the vectorized engine
(`--vec`) DAPHNE crashes with the following error:
```
loc("./scripts/algorithms/multiLogReg.daph":223:40): error: operand #0 does not dominate this use
module  { ...
```
Please find attached [file](https://github.com/daphne-eu/daphne/files/8747284/multiLogReg.txt) to view the whole error.

**Comment by pdamme** [comment]
Thanks for reporting this bug, @aristotelis96. The problem is that the MLIR SSA value `%187` is used (line 523) before it is defined (line 620) in the IR produced by `VectorizeComputationsPass` (see the file you attached). Of course, that should not happen. Apparently, something goes wrong while fusing operations into vectorized pipelines, probably some dependencies between the values are not accounted for correctly.

I will try to solve it.
