### ISSUE TITLE
Kernel for EigenOp

### ISSUE THREAD

**Issue by pdamme** [daphne-eu/daphne#391]
We need a kernel for DaphneIR's `EigenOp`, which calculates both the eigen values and the eigen vectors of the given matrix.

**Comment by pdamme** [comment]
Currently, we need it for the DaphneDSL script `scripts/algorithms/pca.daph` (line 72).

**Comment by KostasBitsakos** [comment]
Ι took a thorough look on the issue and I have some comments.
Let me firstly comment, that I am not an expert on the field, I conducted however some research.

In my understanding based on the deliverables we would like to work mostly with blas/lapack as a third party library for the linear algebra operations.
Though I think a cpp library called eigen  (https://eigen.tuxfamily.org/index.php?title=Main_Page) would be a better fit for extracting the eigen values and eigen vectors of a given matrix.

Firstly, I think because lapack is written in Fortran its API is very FORTRAN-like and thus more demanding in terms of coding.
Many users adress this issue and that the learning curve is large. (although there is the lapack++ implementation which users suggest to be somehow more cpp user-friendly).

Eigen has also some crucial advantages over lapack such as:
- Eigen handles fixed-size matrices and vectors, which are very widely used.
- Eigen has built-in support for sparse matrices and vectors.
- Eigen provides a lot of convenience features (see Geometry module, Array module, etc), which are also very widely used.

Finally in terms of performance, eigen is proven to outperform blas/lapack.
It takes advantage of cpp advanced features to optimize one's code and make most things compile-time and SIMD/vectorized.

I repeat I am not an expert on the field, nor I have ever coded using eigen or blas or blas/lapack. 
But I think this would be the best way to go.
I would like some comments before procceding in coding, that's why I am sharing my thoughs here.

PS: After our Wp4-Wp5 meeting, today at 29-06-2022 I checked about eigen's license.
It's MPL 2.0 (Mozilla Public License).

**Comment by corepointer** [comment]
Imho using Eigen is fine. Currently we use OpenBLAS as our CPU BLAS/LAPACK implementation. From the quick read on Eigen's documentation, their library can make use of OpenBLAS (and other implementations like Intel's MKL). So I guess it's fine to add Eigen as a dependency if they provide a solid implementation. Our dependency compile time is already quite long anyway :D Just make sure that the compile time dependency is reasonably contained.
I'm no expert on the license issue tbh. I hope MPL is ok.

**Comment by KostasBitsakos** [comment]
Hello,

working with the Eigen library in order to construct the kernel, during testing I encountered some tricky corner cases.
The main issue is that eigen values, can be complex numbers.
The problem is that Daphne does not support complex value types.

Although this issue can easily be bypassed, if we use the eigen kernel strictly for the PCA algorithm, as the PCA uses the covariance matrix, which is a real symmetric matrix, so its eigenvalues should be real. 
Some suggest that sometimes the numerical eigen algorithms, might return small imaginary components due to roundoff error. And that these imaginary components, can be ignored.

If that's the case I can make sure that the eigen kernel will return only the real part of the eigen values.
Shall i proceed like that?

**Comment by pdamme** [comment]
Good catch @KostasBitsakos! At the moment, DAPHNE does not support complex numbers as a value type, but we plan to add that later via the means for extensibility we are currently working on.

For now, I suggest circumventing this problem. I've also just read that up again: the eigenvalues and eigenvectors of a real and symmetric matrix are always real (not complex). So let's assume that the input matrix of `eigen()` is symmetric (we should update this in the documentation of the [DaphneDSL built-in functions](https://github.com/daphne-eu/daphne/blob/main/doc/DaphneDSLBuiltins.md#matrix-decomposition--co)). So **yes, please proceed by ignoring the imaginary components** returned by the eigen library.

*Side-note*: DaphneDSL's built-in functions are strongly inspired by those of [SystemDS's DML](https://apache.github.io/systemds/site/dml-language-reference). Futhermore, we plan to automatically translate many of the higher-level ML algorithms of SystemDS to DaphneDSL automatically (#197), to get a large library of such algorithms without having to reimplement them. SystemDS's built-in function [`eigen()`](https://apache.github.io/systemds/site/dml-language-reference#linear-algebra-built-in-functions) also assumes a symmetric input matrix. So even by making this assumption, we will still be able to execute all algorithms translated from SystemDS, which is quite a lot. If need be, we will support non-symmetric inputs to `eigen()` once we support complex numbers.
