### ISSUE TITLE
DaphneDSL: Built-in functions sum and mean

### ISSUE THREAD

**Issue by RetoKrummenacher** [daphne-eu/daphne#393]
The built-in functions sum and mean are used differently in DaphneDSL. 

Sum() for instance is usable with arguments: 0 = row wise, 1 = column wise, none = all and working fine:

```
m = fill(2.0,5,2);
print(sum(m)); # overall
print(sum(m, 0)); # row wise
print(sum(m, 1)); # column wise
```
![image](https://user-images.githubusercontent.com/71382164/171834109-43d8044c-b828-44db-90c0-44e88cce67bd.png)

However, this is different with mean() where only column wise mean is possible.
```
m = fill(2.0,5,2);
# working
print(mean(m, 1)); # cloumn wise
# not working
print(mean(m)); # overall
print(mean(m, 0)); # row wise
```
![image](https://user-images.githubusercontent.com/71382164/171834675-1983b56e-e97b-4f25-afba-6927990eafac.png)

**Comment by aristotelis96** [comment]
Thanks @RetoKrummenacher for reporting this issue. This happens because currently runtime only supports `mean` for column-wise aggregation. In order to support row-wise and all-matrix `mean` aggregation we need to:

1. Extend `src/runtime/local/kernels/AggAll.h` kernel for **all-matrix** `mean` aggregation.
2. Extend `src/runtime/local/kernels/AggRow.h` kernel for **row-wise** `mean` aggregation.
3. Add the corresponding instantiations at `src/runtime/local/kernels/kernels.json`.
4. (Optionally) Test cases.

**Hints**:

- You can see at `src/runtime/local/kernels/AggCol.h` how `mean` is handled for column-wise aggregation. 

Regarding `stddev`, for me it only works for column-wise aggregation (similar to `mean`). `var` is not supported at all for now.

**Comment by RetoKrummenacher** [comment]
Thanks @aristotelis96 for the comment. I agree and hence, I created two separate issues for stddev() #395  and var() #396.
