### ISSUE TITLE
DaphneIR operations on scalars via MLIR std/math operations

### ISSUE THREAD

**Issue by daphne-eu** [daphne-eu/daphne#42]
In GitLab by @pdamme on May 12, 2021, 20:56

DaphneIR is the MLIR/LLVM-based intermediate representation used by the DAPHNE compiler. Currently, almost every operation is lowered to a call to a pre-compiled C++ kernel. In most cases the overhead of a function call is amortized by processing large chunks of data in each call. However, at the moment, even unary and binary operations on scalars (such as `+`, `*`, `log()`, ...) are lowered to kernel calls. When both operands and, thus, the result are scalars, the overhead of calling a kernel can be avoided by lowering these DaphneIR operations to the corresponding operations from MLIR's `llvm` and `math` dialects.

In fact, an earlier version of the prototype was capable of doing that for *a few* binary operations. However, for consistency this feature was removed in commit 2bc79f7481b7eaa59e36a05e6fe5bcdc149ff05f. It would be great to re-introduce this feature in a systematic way for as many unary/binary functions as possible.

The task is to implement (C++) a compiler pass lowering DaphneIR's `EwUnaryOp` and `EwBinaryOp` on scalars to the appropriate operations from the MLIR `llvm` and `math` dialects. From that point, existing lowering passes can be applied to JIT-compile executable code. Special care should be taken to ensure that these MLIR operations yield *exactly the same* results as our pre-compiled kernels for scalars. The reason is that those scalar kernels are re-used in the elementwise kernels for matrices/frames. Thus, any inconsistent behavior would be counter-intuitive. Note also that this should hold for *all* supported value types. It shall be possible to turn off the new pass. Then, script-level tests could be used to compare the results with and without this feature.

**Comment by pdamme** [comment]
The basic idea of the earlier implementation we had before was (feel free to have a look at the commit mentioned above):
1. Define certain unary/binary ops as legal in `RewriteToCallKernelOpPass` iff they work only on scalars. That way, they won't be replaced in that pass.
2. Lower these DaphneIR ops to ops from MLIR's `llvm`/`math` dialects in `LowerToLLVMPass`.

Following this approach again might be easier than introducing a separate pass due to the required MLIR type conversion. But both approaches should be possible.

**A few pointers**
- MLIR's [`math` dialect](https://mlir.llvm.org/docs/Dialects/MathOps/)
- MLIR's [`llvm` dialect](https://mlir.llvm.org/docs/Dialects/LLVM/)

**Comment by philipportner** [comment]
Please assign this issue to me @pdamme .

**Comment by philipportner** [comment]
Closed with #633
