### ISSUE TITLE
Timing - Profiling support

### ISSUE THREAD

**Issue by aristotelis96** [daphne-eu/daphne#423]
Both the end-user and developers of DAPHNE should be able to get timing statistics regarding various steps of execution and get insight and understanding on where most time is spent. A few examples could be:

- Time spent compiling and executing a DSL script.
- Time spent executing dividual pipelines.
- Time spent executing individual kernels (potentially per pipeline).

This issue is to further discuss the best way to approach this. Some examples for discussion:

- Architectural design.
- Libraries or frameworks that could be used.
- Where we should measure time (e.g., Before/after calling a kernel etc.).
- Ways to inform the user about the result (e.g., output file, printing, etc.) and what additional data should be provided (e.g., pipeline code, kernel name, etc.).

**Comment by jonnygiger** [comment]
When it comes to outputting the result to a file, Clang has a very clean implementation of this worth taking a look at:

[https://github.com/aras-p/llvm-project-20170507/pull/2/files#diff-8289d7b6556cc50e792f2c015a05b3efbeba5eacf8e5319b39cb1f082f1b71b5](https://github.com/aras-p/llvm-project-20170507/pull/2/files#diff-8289d7b6556cc50e792f2c015a05b3efbeba5eacf8e5319b39cb1f082f1b71b5)

**Comment by pdamme** [comment]
Timing for the high-level steps of DAPHNE has been addressed in 004e67bda6c4efd0cae43f258625c7609ad7b578, which introduced the `--timing` command-line argument.

Moreover, this issue is related to #227, which was addressed in d4cf91031dcebe2467ca9b07c9e651c77f3917ff by introducing the `--statistics` command-line argument.

This timing information is not used by system-internal components (e.g., scheduling) yet, but I think, we could close this issue nevertheless and create more specific follow-up issues when necessary.

So I will close this issue now, but feel free to re-open if you disagree.
