### ISSUE TITLE
Moving bin folder outside build

### ISSUE THREAD

**Issue by AhmedEleliemy** [daphne-eu/daphne#454]
@corepointer 
I had the latest commit aa6ef4a20254e12517c7a8acb5beee755d1726f3.
After building the solution. I tried to execute the one script "connected component". However, it now gives the following error
command
`./bin/daphne --vec --num-threads=4 --pin-workers --GSS --PERGROUP --select-matrix-representations --args f=\"./Amazon0601_0.csv\" components_read.daphne ` 
output
Parser error: [json.exception.parse_error.101] parse error at line 1, column 7: syntax error while parsing value - unexpected ','; expected end of input

Luckily, I still have the old build binary under build/bin/daphne so I tried
command
 `./build/bin/daphne --vec --num-threads=4 --pin-workers --GSS --PERGROUP --select-matrix-representations --args f=\"./Amazon0601_0.csv\" components_read.daphne `
 and it worked 
 
 Any suggestions?

**Comment by aristotelis96** [comment]
I had a similar issue, turns out I was using the old file metadata format. Have you tried updating the metadata (amazon0601_0.csv.meta)? See [here](https://github.com/daphne-eu/daphne/blob/main/doc/FileMetaDataFormat.md). Also, in addtition to the metadata file, the csv format needs to to be updated to .mtx format (see [here](https://math.nist.gov/MatrixMarket/formats.html)). 

E.g. old `.csv` format: 

    0,1
    1,2
     ...

`.mtx` format:

      %%MatrixMarket matrix coordinate integer general
      NUM_ROWS NUM_COLUMNS NUM_VALUES
      0 1 value
      1 2 value
      ....

Hope this helps.

**Comment by AhmedEleliemy** [comment]
thanks @aristotelis96  I have not notice the change in the metadata file. So, it works now thanks a lot

**Comment by pdamme** [comment]
FYI: I've just added this to the [list of common errors/mistakes](https://github.com/daphne-eu/daphne/blob/main/doc/RunningDaphneLocally.md#typical-errors-and-troubleshooting) when executing `daphne` locally.

Sorry for the inconvenience, @AhmedEleliemy. In the future, we should inform everyone of such API changes (and not just add it to the [documentation](https://github.com/daphne-eu/daphne/blob/main/doc/FileMetaDataFormat.md)). The mailing list would be an ideal channel. Unfortunately, the public mailing list did not really take off (due to technical problems). The old internal mailing list is not suitable for involving interested people outside of the DAPHNE project. We need to find a solution soon.
