### ISSUE TITLE
Behavior of build.sh --clean

### ISSUE THREAD

**Issue by corepointer** [daphne-eu/daphne#466]
Our build script has two types of cleaning the source tree:
* **--clean**: removes the DAPHNE build directories **and** the dependencies
* **--cleanAll**: everything that --clean does plus downloaded packages and extracted 3rd party sources

Imho this would be more practical:
* --clean: remove bin, build, lib from DAPHNE source tree
* --cleanAll: all from --clean plus compiled 3rd party deps
* --cleanDownloadCache: (name is just a suggestion) remove the downloaded packages and extracted sources

The idea originated from how often I needed one of these three in the past.

**Comment by pdamme** [comment]
Hi @corepointer, I think this is a very good idea, especially since it allows removing the DAPHNE-specific artifacts without removing anything from the third-party dependencies.

I also agree with what these three steps should remove. Regarding the wording, I suggest:

`--clean`: removes `bin`, `build`, `lib`
`--cleanDeps`: removes `thirdparty/build`, `thirdparty/installed`, `thirdparty/*.install.success`, `thirdparty/llvm-last-built-commit.txt`
`--cleanCache` (or `--cleanDownloads`): removes `thirdparty/download-cache`, `thirdparty/sources`, `thirdparty/*.download.success`, and `thirdparty/llvm-project` (except for `thirdparty/llvm-project/.git`)

`--cleanAll`: combines `--clean`, `--cleanDeps`, and `--cleanCache`

The first three options remove disjoint sets of directories/files. Then, to my mind, `--cleanAll` should really remove *all* of them.

**Comment by corepointer** [comment]
Thx for your comments @pdamme  I'll make it so ;-)
