### ISSUE TITLE
Improved Apache Arrow integration

### ISSUE THREAD

**Issue by corepointer** [daphne-eu/daphne#473]
We use Apache Arrow for reading Parquet format. The initial integration can be improved in several ways:
* Use a more up to date *release* version (we currently use some development snapshot)
* Move the CMake config to src/runtime/local/kernels/CMakeLists.txt as this only concerns kernels
* Remove the hard coded paths in the CMake config (the release version can be used with just a ``find_package(Arrow REQUIRED)``
* Make Arrow non-optional: We can remove the --arrow from build.sh and USE_ARROW preprocessor macro as this is an "internal" dependency we can build ourselves (in contrast to --cuda for example, which needs a system wide driver install)
* There's a TODO in the code returning a null pointer upon failure. As this is not documented any further this should be rather changed into a runtime exception than continue execution and using (!) that null pointer to subsequently crash somewhere else.

**Comment by pdamme** [comment]
Thanks for bringing this up. See #331 and #345 for some older conversation on the integration of Arrow and Parquet. I think back then we used a development snapshot of Arrow because we needed some new features which were not included in a release yet. Switching to an official Arrow release is a good idea.

Making Arrow a required dependency is okay if it doesn't cause problems, which I hope won't be the case with an official release.
