### ISSUE TITLE
Distributed wrapper issue

### ISSUE THREAD

**Issue by AhmedEleliemy** [daphne-eu/daphne#475]
The function getPipelineInputTypes is no longer functioning. 
The error is always. 
loc("-":1:1): error: Dialect `func' not found for custom op 'func.func.
The source of the error is the following line
 mlir::OwningOpRef<mlir::ModuleOp> module(mlir::parseSourceString<mlir::ModuleOp>(mlirCode, &ctx));

For example, I have printed the MLIR code that is passed to the function, it looks as follows
func.func @dist(%arg0: !daphne.Matrix<?x15xf64:sp[1.000000e+00]>, %arg1: f64) -> !daphne.Matrix<?x?xf64> {
  %0 = "daphne.ewAdd"(%arg0, %arg1) : (!daphne.Matrix<?x15xf64:sp[1.000000e+00]>, f64) -> !daphne.Matrix<?x?xf64>
  "daphne.return"(%0) : (!daphne.Matrix<?x?xf64>) -> ()
}
@pdamme @corepointer @aristotelis96  any ideas/suggestions?

**Comment by pdamme** [comment]
I suspect that the MLIR `func` dialect is not registered correctly. This dialect was added with our recent MLIR upgrade. However, in `src/runtime/distributed/coordinator/kernels/DistributedWrapper.h`:`getPipelineInputTypes()`, unregistered dialects should be fine, since we say `ctx.allowUnregisteredDialects();`...

I need to have a closer look, but since all test cases pass successfully (on main): **Can you please share some details on how to trigger this error?** (How do you invoke `daphne` etc.)

**Comment by AhmedEleliemy** [comment]
Thanks @pdamme  I am not sure how you can reproduce it. I mean it only appears if you go through the DistributedWrapper.h, i.e., I am not sure what are the test cases that you rerun. do they include any distributed "e.g., gRPC" kernels?
The way I come to this error: I merged the main DAPHNE into my fork 
https://github.com/AhmedEleliemy/daphne
You can clone it and run the following command
mpirun --allow-run-as-root -np 4 ./bin/daphne --distributed --vec scripts/examples/hello-world.daph
does it make sense?

I think the same thing should happen to the gRPC as well
@aristotelis96 can you confirm?

**Comment by aristotelis96** [comment]
I just looked into it and yes the error appears with the gRPC as well. @pdamme you can reproduce it on the main branch if you run distributed daphne. The steps are:

1. Build and run a distributed worker: `./build.sh --target DistributedWorker; ./bin/DistributedWorker localhost:5000`
2. On another terminal, set enviromental variable `export DISTRIBUTED_WORKERS=localhost:5000`
3. run distributed daphne `./bin/daphne --distributed example.daphne`

The issue should also be present on the worker (`src/runtime/distributed/worker/WorkerImpl.cpp`) when parsing the MLIR fragment for execution (which now never happens since DistributedWrapper crashes before that step).

**Comment by aristotelis96** [comment]
I think the issue is not loading `FuncDialect` on the `MLIRContext` object. I was able to fix this by adding:
`ctx.getOrLoadDialect<mlir::func::FuncDialect>();`, will open a PR shortly.

Tests use the `Compute` function from the `WorkerImpl.cpp` which creates a `DaphneIrExecutor` and get's the context object from there. `DaphneIrExecutor`'s constructor correctly loads the FuncDialect which results in tests passing correctly and not causing any issues on the worker implementation.

**Comment by pdamme** [comment]
Thanks, but you don't need to, I'm about to commit a fix :) .

**Comment by pdamme** [comment]
For some background: Even though we allow unregistered dialects at that point by `ctx.allowUnregisteredDialects();`, we need to register the func dialect to make it work, most likely because the operation `func.func` has a custom assembly format, which cannot be parsed unless the dialect is registered. That's my explanation...

**Comment by aristotelis96** [comment]
Thanks @pdamme for confirming the fix and providing the explanation. I'll push the fix soon. :)

**Comment by pdamme** [comment]
> Tests use the `Compute` function from the `WorkerImpl.cpp` which creates a `DaphneIrExecutor` and get's the context object from there. `DaphneIrExecutor`'s constructor correctly loads the FuncDialect which results in tests passing correctly and not causing any issues on the worker implementation.

That is true for the unit tests in `test/runtime/distributed/worker/WorkerTest.cpp`. However, we also have script-level tests (which invoke `daphne` as a separate process, so we go through the entire parser/compiler/runtime -stack) for distributed execution in `test/api/cli/distributed/DistributedTest.cpp`. Line 60 in that file specifies only the `--vec` flag, which used to be sufficient to trigger distributed execution if the environment variable `DISTRIBUTED_WORKERS` is set. Meanwhile, this behavior was changed, now `--distributed` must be given. I've just fixed this in the test case in 20080d78f8278b678c70b6068cf53aff39f1a1ce.
