### ISSUE TITLE
Running ./build-containers.sh without WSL internet connection

### ISSUE THREAD

**Issue by bl1zzardx** [daphne-eu/daphne#477]
I do not have a unix client, and within WSL I do not have a connection to the internet. So I am cloning from GitHub via windows. This requires me to set  `git config --global core.autocrlf false`, clone it, and then move it into WSL file system. Docker Desktop is installed on my Windows system and "Use WSL 2 based engine" is enabled - therefore it is available within my WSL-ubuntu. Now I also had to follow these steps to get it to work: [stackoverflow.com](https://stackoverflow.com/questions/48957195/how-to-fix-docker-got-permission-denied-issue). Now docker run hello-world works. In the screenshot below I want to show the way I call the build-containers.sh and that I cannot ping 8.8.8.8. If there are pre-build containers that I can get from docker via Windows, I'd be very happy.

![2023-03-03_12h20_56](https://user-images.githubusercontent.com/75115887/222707613-c4534bdd-d325-413a-b4d6-147df618551f.png)

**Comment by corepointer** [comment]
Does your WSL lack networking due to security reasons or is it a configuration issue or some other problem?
It is (almost) absolutely necessary that you have a functional network connection in WSL as a constant back and forth between Windows and WSL would be *very* inconvenient. 

Maybe this [stackoverflow](https://stackoverflow.com/questions/62314789/no-internet-connection-on-wsl-ubuntu-windows-subsystem-for-linux) entry helps (accepted answer is the second answer).

Transferring a docker container without networking is possible if you save the container to a tar archive and load it in WSL. [This how-to](https://www.baeldung.com/ops/share-image-without-docker-hub) should help you there. But then you should make sure that you don't need to build dependencies (which would need to be downloaded). An image with prebulid DAPHNE binaries are still on my todo list.

hth, Mark

**Comment by bl1zzardx** [comment]
The lacking network is not for security reasons, but rather a configuration problem. Thanks to your hint Mark, I ended up getting it to work, because the company network / VPN rerouted me (nowhere). Maybe this was what helped me in the end [stackoverflow](https://stackoverflow.com/questions/66444822/wsl-2-dns-is-not-working-with-vpn-connection-on-win-10). Now the container building process is running.

**Comment by corepointer** [comment]
Thx for the update. 
Now that your network connection is working, you can also use the shortcut of pulling pre-built images. But I guess that'll be more interesting once we have the DAPHNE binaries included as well.
