### ISSUE TITLE
Exception handling on ARM

### ISSUE THREAD

**Issue by corepointer** [daphne-eu/daphne#555]
Currently DAPHNE source code throws exceptions across "binary boundaries" which is said to be bad practice and apparently not supported on ARM (there, abort() is called due to the uncaught exceptions). This means that, for example, exceptions in a shared library like libAllKernels.so need to be caught in that shared library as they do not get passed on to the main executables like daphne and run_tests. Seems to also be a problem with static linking as the problem already showed up in the MLIR compilation stages (some SQL test case that is supposed to throw an exception and return StatusCode::PASS_ERROR revealed the problem). 

I fixed the problem and will push after cleanup and further testing. The solution concerning shared libs involves the use of signals which might lead us to Linux or at least POSIX dependence. But that is fine for now I guess. If some day we need a port to a non-POSIX system (e.g., Windows?), a solution involving their API can be implemented.

**Comment by pdamme** [comment]
Thanks for bringing up this point, @corepointer. I wasn't aware of this problem (it doesn't seem to occur in the environments where I have used DAPHNE so far), but would be interested in your solution, since I can imagine it could have quite some impact on the way we handle exceptions/errors in DAPHNE.
