### ISSUE TITLE
[DSL] idxMin / idxMax does not work properly

### ISSUE THREAD

**Issue by m-birke** [daphne-eu/daphne#589]
Assuming matrix M:

```
DenseMatrix(3x1, double)
1.11791e-06
5.90741e-07
3.08534e-09
```

`idxMin(M, 1);` produces:

```
JIT session error: Symbols not found: [ _idxminCol__DenseMatrix_size_t__DenseMatrix_size_t ]
JIT-Engine invocation failed: Failed to materialize symbols: { (main, { _mlir_main, main, calcTriangles-1-1, _mlir_ciface_main, _mlir_ciface_toTerminate-2-2, toTerminate-2-2, _mlir_calcTriangles-1-1, _mlir__mlir_ciface_calcTriangles-1-1, _mlir_toTerminate-2-2, _mlir__mlir_ciface_main, _mlir__mlir_ciface_toTerminate-2-2, _mlir_ciface_calcTriangles-1-1 }) }Program aborted due to an unhandled Error:
Failed to materialize symbols: { (main, { _mlir_main, main, calcTriangles-1-1, _mlir_ciface_main, _mlir_ciface_toTerminate-2-2, toTerminate-2-2, _mlir_calcTriangles-1-1, _mlir__mlir_ciface_calcTriangles-1-1, _mlir_toTerminate-2-2, _mlir__mlir_ciface_main, _mlir__mlir_ciface_toTerminate-2-2, _mlir_ciface_calcTriangles-1-1 }) }
[2023-08-16 15:21:38.480] [error] Got an abort signal from the execution engine. Most likely an exception in a shared library. Check logs!
[error]: Execution error: Returning from signal 6
```

`idxMin(M, 0);` produces:

```
DenseMatrix(3x1, uint64_t)
0
0
0
```

Assuming Matrix N:

```
DenseMatrix(3x2, double)
1.11791e-06 1e-10
5.90741e-07 1e-10
3.08534e-09 1e-10
```

`idxMin(N, 0);` produces

```
DenseMatrix(3x1, uint64_t)
0
0
0
```

**Comment by corepointer** [comment]
Hi!

Answering to your three observations from top to bottom:

1. The idxMin for column aggregates is simply not implemented (see ``kernels.json`` line 41-97. Adding "IDXMIN" and "IDXMAX" to line 96 and a recompile of DAPHNE might be all that is needed here.
2. To my understanding this one behaves correctly. You are asking for the index of the minimum value in each row of a vector that has three rows and one column. So that one item in each row is the minimum in its row. Hence the result is index 0 for each row (zero based indexing).
3. With your matrix N the result should not be three times zero. There you've hit a "bug" which is documented as a "ToDo" in line 40 of ``AdaptTypesToKernelsPass.cpp`` As a workaround you can add  
``[["DenseMatrix", "size_t"], ["DenseMatrix", "double"]],`` somewhere to the instantiations section of ``AggRow`` starting at line 165 in  ``kernels.json`` and recompile DAPHNE.

hth, Mark :beach_umbrella:

**Comment by pdamme** [comment]
Thanks for reporting this bug, @m-birke. I can confirm @corepointer's answers. I'm working on a fix.
