### ISSUE TITLE
Online documentation does not render table/TeX for DaphneDSL trig functions

### ISSUE THREAD

**Issue by AlexRTer** [daphne-eu/daphne#673]
The table and TeX snippets for `Trigonometric/Hyperbolic` functions at https://github.com/daphne-eu/daphne/blob/main/doc/DaphneDSL/Builtins.md#trigonometrichyperbolic display as expected on github.
However, the online documentation https://daphne-eu.github.io/daphne/DaphneDSL/Builtins/ does not render either of them correctly and instead displays mostly unformatted text and symbols.

**Comment by pdamme** [comment]
Thanks for flagging this issue @AlexRTer. It seems like MkDocs, the tool we use for generating HTML documentation from our Markdown files, does not support LaTeX out of the box. Maybe @m-birke knows more.

**Comment by m-birke** [comment]
Hi @AlexRTer github has its own md flavor, while we use mkdocs with the material theme to build our html representation, in the best case we find sth that works for both so that it can be rendered for both. It seems that both mkdocs-material and github support mathjax

https://squidfunk.github.io/mkdocs-material/reference/math/
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions

KR
