### ISSUE TITLE
DaphneDSL loops crash after a certain number of iterations

### ISSUE THREAD

**Issue by daphne-eu** [daphne-eu/daphne#77]
In GitLab by @pdamme on Jun 12, 2021, 20:00

The following two simple programs both crash with a segfault after approximately 261800 iterations. The precise number of iterations is individual for each attempt:

```
for(i in 1:1000000)
    print(i);
```

```
i = 0;
while(i < 1000000) {
    print(i);
    i = i + 1;
}
```

The reason is unclear, but might be some kind of memory leak due to the way we call kernels.

Furthermore, endless loops also crash with a segfault. It is unclear if this has the same cause.

```
while(1==1)
    i = 1;
```

-----

This is not a very urgent problem, but might indicate that something is going wrong internally.

**Comment by J-Brest** [comment]
After some works, it seems that the stack size might be problem.

**Comment by borkob** [comment]
By increasing the stack size, the above program works.
Command to increase stack size (ubuntu):
ulimit -s 6400000

**Comment by J-Brest** [comment]
# 
#  in bash:   ulimit -s 6400000
#

start = now();

sum = 0;
for(i in 1:100000)
   sum = sum + i;    
print(sum);
 
sum = 0;
for(i in 1:1000000)
   sum = sum + i;    
print(sum);

sum = 0;
for(i in 1:10000000)
   sum = sum + i;    
print(sum);
 
end=now();
print("Time: "+(end-start)/1000000000.0 + " s");

On linux Mint now it works:
 ../bin/daphne myFor.daph 
5000050000
500000500000
50000005000000
Time: 0.249489 s

**Comment by pdamme** [comment]
Thanks for joining the discussion @J-Brest and @borkob. I'm happy to hear that you have found a workaround. I can confirm that increasing the stack size circumvents the problem. This observation is consistent with our suspicion from back then that the problem is related to a memory leak (of allocations on the stack).

Increasing the stack size as you suggest can already be very helpful to users. However, I think it only addresses the symptom, not the root cause. For instance, if you only slightly increase the stack size, DAPHNE can do only slightly more iterations. However, it's hard to know how large the stack needs to be to permit enough iterations. Ideally, we want to permit any number of iterations.

I think a solution of the underlying problem requires some work in the `LowerToLLVMPass` of the DAPHNE compiler (see `src/compiler/lowering/LowerToLLVMPass.cpp`), more specifically to the way we call kernels. Any help would be highly appreciated. Meanwhile, this is an important problem since it's actually blocking users.

**Comment by philipportner** [comment]
As @pdamme already mentioned, improving the `LowerToLLVMPass` and our calling conventions for kernels would enable us to solve this in possibly multiple ways.

- not having `alloc` inside the loop at all
- using passes to hoist this outside of the loop such as `LoopInvariantCodeMotionPass` or `BufferLoopHoistingPass` (though that one refers to `memref.alloc` ops)

I tried to use existing passes to see if I could solve this without refactoring too much code but as `LowerToLLVMPass` removes the loop and inserts the alloc at the same time, none of the existing passes work in that case as these seem to only work with ops having the `LoopLikeOpInterface`.
